<?php
use livefactory\modules\sales\includes\NumeroALetras;
$office = $model->office;
$temp3  =  \livefactory\models\Office::find()->where('id = 14')->all();
$temp4 = \livefactory\models\Office::find('id = 19')->all();
if ($office->id == 2 and $model->added_at < 1553666400) {
    $office = $temp3[0];
    $office->code = 'CC';
}
if ($office->id == 13 and $model->added_at < 1561266000){
    $office = $temp4[17];
    $office->code = 'M2';
}
$logo = ($office->code == 'CC' || $office->code == 'C1') ? ($model->added_at < 1553666400 ? 'tuefectivo2' : 'tuefectivo') : ($office->code == 'G3' ? 'metropoli' : ($office->code == 'M1' ? 'apoyofinanciero' : ($office->code == 'MX' ? 'efectivida' : ($office->code == 'L1' ? 'efectivida' : ($office->code == 'D1' ? 'business' :  ($office->code == 'G4' ? 'multi-servicios' : ($office->code == 'M2' ? ($model->added_at < 1561352400 ? 'avantti' : null) : ($office->code == 'G5' ? ($model->added_at >= 1579672800 ? 'one-capital': null ) : ($office->code == 'P1' ? 'impulsa' : ($office->code == 'P3' ? 'logo_gplaneacion' : null))) )))))));
$file = '../office/'.$office->id.'.png?v'.$office->updated_at;
?>

<table border="0" cellpadding="0" cellspacing="0" class="cover">
    <tbody>
    <?php if (file_exists($file)){?>
        <tr>
            <td style="text-align: center"><img alt="image" src="<?=$file?>" height="<?= $office->height_document?>" /></td>
        </tr>
    <?php } else{
        if ($logo ){?>
            <tr>
            <td style="text-align: center"><img alt="image" src="../logo/<?=$logo?>.jpg?v<?=$office->updated_at?>" height="<?= $office->height_document?>" /></td>
        </tr>
    <?php } } ?>
    <tr>
        <td class="text-center">
            <strong>CONTRATO DE PRESTACIÓN DE SERVICIOS</strong><br><br><br>
        </td>
    </tr>
    <tr>
        <td class="text-justify">
            <p>CONTRATO DE PRESTACIÓN DE SERVICIOS PROFESIONALES DE GESTORÍA E INTERMEDIACIÓN QUE CELEBRAN POR UNA PARTE: <strong><?=$office->business_name;?></strong> A QUIEN EN LO SUCESIVO SE LE DENOMINARÁ “EL PRESTADOR DE SERVICIOS”, Y POR LA OTRA EL(LA) C. <strong><?=strtoupper($model->lead_name)?></strong> A QUIEN EN LO SUCESIVO SE LE DENOMINARA "EL CLIENTE" QUIENES FIRMAN AL FINAL DEL PRESENTE CONTRATO, SUJETÁNDOSE AL TENOR DE LAS SIGUIENTES:</p>
            <p>&nbsp;</p>
            <p class="text-center"><strong>D E C L A R A C I O N E S</strong></p>
            <p>&nbsp;</p>
            <p><strong>DECLARA "EL PRESTADOR DE SERVICIOS":</strong></p>
            <ol type="A">
                <li>SER UNA EMPRESA (PERSONA MORAL) DEBIDAMENTE CONSTITUIDA BAJO LAS LEYES MEXICANAS CUYA PERSONALIDAD QUEDA DEBIDAMENTE ACREDITADA BAJO EL INSTRUMENTO NOTARIAL <?=is_numeric($office->notary_id) ? NumeroALetras::convertir($office->notary_id) : strtoupper($office->notary_id)?>, PASADO ANTE LA FE DEL NOTARIO PÚBLICO LICENCIADO <?=strtoupper($office->notary)?>, TITULAR DE LA NOTARIA <?=is_numeric($office->notary_number) ? NumeroALetras::convertir($office->notary_number) : $office->notary_number?>, DE LA CIUDAD DE <?=strtoupper($office->notary_state)?>.</li>
                <li>CONTAR CON LA EXPERIENCIA NECESARIA ANTE DIFERENTES INSTITUCIONES FINANCIERAS , BANCARIAS Y ORGANIZACIONES AUXILIARES DE CREDITO, LO QUE LE PERMITE REALIZAR GESTIONES DE INTERMEDIACIÓN CREDITICIA.</li>
            </ol>
            <p><strong>DECLARA "EL CLIENTE":</strong></p>
            <ol type="A">
                <li>CONTAR CON LA CAPACIDAD LEGAL PARA FIRMAR EL PRESENTE CONTRATO.</li>
                <li>CONTAR CON LA SOLVENCIA PARA AFRONTAR LOS COMPROMISOS DE PAGO DERIVADOS DEL PRESENTE CONTRATO.</li>
                <li>QUE ES SU DESEO, ENTERA, TOTAL Y LIBRE VOLUNTAD LA CONTRATACIÓN DEL SERVICIO QUE "EL PRESTADOR DE SERVICIOS" LE OFRECE.</li>
            </ol>
            <p>MANIFESTADO LO ANTERIOR, LAS PARTES ACUERDAN BAJO LAS SIGUIENTES:</p>
            <p class="text-center"><strong>CLÁUSULAS</strong></p>
            <ol type="I">
                <li><strong>PRESTACION DE SERVICIO.</strong> LA PRESTACIÓN DE SERVICIOS SE LIMITARÁ A LAS SIGUIENTES ACTIVIDADES:
                    <ul>
                        <li>CONOCER EL NIVEL DE ENDEUDAMIENTO Y LA CAPACIDAD DE PAGO DEL CLIENTE, PARA DETERMINAR LA VIABILIDAD DE LA GESTIÓN.</li>
                        <li>CONCLUIDA LA VIABILIDAD QUE DETERMINARÁ EL PROCEDIMIENTO DE GESTIÓN Y SOLO SI "EL CLIENTE" MANIFIESTA SU VOLUNTAD DE LLEVAR A CABO LA PRESENTE CONTRATACIÓN, "EL PRESTADOR DE SERVICIOS" HARÁ RECEPCIÓN DE LA DOCUMENTACION QUE EL CLIENTE EXPIDA Y LA TURNARÁ AL ÁREA CORRESPONDIENTE PARA LLEVAR A CABO LA GESTIÓN ANTE ALGUNA INSTITUCIÓN DE CRÉDITO O FINANCIERA TALES COMO SOFOL, SOFOM, SOFIPO, BANCOS, INFONAVIT, FOVISSSTE, CASAS DE EMPEÑO O CUALQUIERA OTRA QUE ESTÉ AL ALCANDE DE "EL PRESTADOR DE SERVICIOS" .</li>
                        <li>PRESTAR SUS SERVICIOS PARA AYUDAR A "EL CLIENTE" A LIQUIDAR, REDUCIR O EN SU CASO REESTRUCTURAR LOS ADEUDOS EN TARJETAS DE CRÉDITO, FRENTE A CUALQUIER INSTITUCIÓN DE CREDITO, O A CUALESQUIERA QUE FUEREN LAS SOCIEDADES QUE OTORGUEN UN CRÉDITO DE CONSUMO, SIEMPRE POR ORDEN Y CUENTA DE "EL CLIENTE" EN LOS TÉRMINOS Y CONDICIONES ESTABLECIDOS</li>
                    </ul>
                </li>
                <li><strong>DOCUMENTACION.</strong> EL PLAZO PARA LA ENTREGA DE LA DOCUMENTACION SERÁ HASTA SIETE DÍAS HÁBILES, CONTADOS A PARTIR DE LA FECHA DE CELEBRACIÓN DEL PRESENTE CONTRATO. ASÍ MISMO SE HACE CONSTAR QUE "EL CLIENTE" SE OBLIGA A ENTREGAR TODOS Y CADA UNO DE LOS DOCUMENTOS Y/O REQUISITOS QUE LE SEAN SOLICITADOS POR "EL PRESTADOR DE SERVICIOS", CON LA ÚNICA FINALIDAD DE LLEVAR A CABO DE MANERA EXITOSA LA GESTIÓN YA ANTES MENCIONADA.
                    <p>SI FUERE EL CASO QUE "EL PRESTADOR DE SERVICIOS" SOLICITASE DOCUMENTACIÓN POSTERIOR A "EL CLIENTE", ÉSTE ÚLTIMO TIENE LA OBLIGACION DE PROPORCIONARLA DENTRO DE UN PLAZO NO MAYOR A LOS 20 DIAS NATURALES, SI SE ABSTIENE POR CUALQUIERA QUE FUERE EL MOTIVO, ESTO CONSTITUIRÁ UNA CAUSAL DE RECISIÓN INMEDIATA.s</p>
                </li>
                <li><strong>USO DE LA INFORMACION.</strong> "EL CLIENTE" AUTORIZA A "EL PRESTADOR DE SERVICIOS" A HACER USO DE LA INFORMACIÓN Y DOCUMENTACIÓN QUE HAYA PROPORCIONADO CON EL FIN DE LLEVAR A CABO EL OBJETO DEL PRESENTE CONTRATO. </li>
                <li><strong>SECRECÍA.</strong> EL CLIENTE SE OBLIGA A MANTENER LA INFORMACIÓN QUE FUERE OBJETO DEL PRESENTE CONTRATO EN ESTRICTA CONFIDENCIALIDAD, QUEDANDO PROHIBIDA LA DIVULGACIÓN O REPRODUCCIÓN A TERCEROS. EN EL ENTENDIDO QUE, DE NO CUMPLIRSE LA PRESENTE CLAUSULA CAUSARÁ UNA RECISIÓN INMEDIATA.</li>
<!--                --><?php //if ($office->id != 3){?>
<!--                    <li><strong>EL PAGO.</strong> UNA VEZ QUE SE EXPRESE EL CONSENTIMIENTO PARA LLEVAR A CABO LA PRESTACIÓN DEL SERVICIO. "EL CLIENTE" ACUERDA PAGAR A "EL PRESTADOR DE SERVICIOS" LA CANTIDAD CONSIGNADA EN EL RECIBO POR CONCEPTO DE PAGO DE HONORARIOS BAJO LAS SIGUIENTES CONSIDERACIONES:-->
<!--                        <ul>-->
<!--                            <li>TODO PAGO DEBERÁ EFECTUARSE EN LAS INSTALACIONES DE "EL PRESTADOR DE SERVICIOS" O EN LAS INSTITUCIONES FINANCIERAS QUE EL PRESTADOR DESIGNE, MISMO QUE DEBERÁ SER DEBIDAMENTE ACREDITADO CON FICHA DE DEPÓSITO, O COMPROBANTE LEGIBLE Y VERIFICABLE<br><br></li>-->
<!--                            <li>SE DARÁ POR NULO CUALQUIER PAGO REALIZADO A PERSONA O INSTITUCIÓN DISTINTA O AJENA A LA DESIGNADA POR "EL PRESTADOR DE SERVICIOS". ASÍ COMO TRANSFERENCIAS BANCARIAS O INTERBANCARIAS, REALIZADAS DE FORMA ELECTRÓNICA O POR INTERNET A LAS MISMAS.</li>-->
<!--                        </ul>-->
<!--                    </li>-->
<!--    --><?php //} else {?>
                    <li>
                        <strong>EL PAGO.</strong>UNA VEZ QUE SE EXPRESE EL CONSENTIMIENTO PARA LLEVAR A CABO EL SERVICIO  "EL CLIENTE" ACUERDA QUE PARA EL CÁLCULO DE LA PRESTACIÓN DEL SERVICIO OBJETO DEL PRESENTE CONTRATO, SE ESTABLECE QUE EL PRESTADOR COBRARÁ POR HONORARIOS UNA CANTIDAD DESDE EL DIEZ POR CIENTO (10 %) DE LA CANTIDAD TOTAL DE LA SUMA DE DINERO QUE EL CLIENTE ORDENE AL PRESTADOR A GESTIONAR EN CRÉDITO, O EN SU CASO, REESTRUCTURAR EN SU FAVOR, BAJO LAS SIGUIENTES CONSIDERACIONES:
                        <ul>
                            <li>
                                TODO PAGO DEBERÁ EFECTUARSE EN LAS INSTALACIONES DE "EL PRESTADOR DE SERVICIOS" O EN LAS INSTITUCIONES FINANCIERAS QUE EL PRESTADOR DESIGNE, MISMO QUE DEBERÁ SER DEBIDAMENTE ACREDITADO CON FICHA DE DEPÓSITO, O COMPROBANTE LEGIBLE Y VERIFICABLE.
                            </li>
                            <li>
                                SE DARÁ POR NULO CUALQUIER PAGO REALIZADO A PERSONA O INSTITUCIÓN DISTINTA O AJENA A LA DESIGNADA POR "EL PRESTADOR DE SERVICIOS". ASÍ COMO TRANSFERENCIAS BANCARIAS O INTERBANCARIAS, REALIZADAS DE FORMA ELECTRÓNICA O POR INTERNET A LAS MISMAS
                                EL CLIENTE RECONOCE QUE PARA LA PRESTACIÓN DEL SERVICIO ES NECESARIA LA EROGACIÓN DE GASTOS ACCESORIOS, TALES COMO GASTOS ADMINISTRATIVOS, DE INVESTIGACIÓN, DE OPERACIÓN, ENTRE OTROS QUE CORREN A CARGO DEL CLIENTE, MISMOS GASTOS QUE SE EXCEPTÚAN AL COSTO DE LA PRESTACIÓN, Y QUE DEBERÁN SER PAGADAS POR EL CLIENTE AL PRESTADOR, POR LO QUE LE DEBERÁN SER REQUISITADOS POR EL PRESTADOR PARA SU PAGO, SEGÚN RESULTE SU PROCEDENCIA.
                            </li>
                        </ul>
                    </li>
<!--    --><?php //}?>
                <li><strong>DESARROLLO DE LA GESTION.</strong>
                    <ul>
                        <li>"EL CLIENTE" DEBERÁ CUMPLIR CON TODOS Y CADA UNO DE LOS REQUISITOS Y GARANTÍAS SOLICITADAS DERIVADAS DEL PRESENTE CONTRATO .</li>
                        <li>UNA VEZ CUBIERTAS LAS SOLICITUDES ANTERIORES, LA INSTITUCIÓN FINANCIERA DETERMINARÁ LA VIABILIDAD DEL CRÉDITO GESTIONADO.</li>
                        <li>"EL CLIENTE" FIRMARÁ EN SU OPORTUNIDAD, DE CONFORMIDAD LA LÍNEA DE CRÉDITO PROPUESTO, POR LA INSTITUCIÓN QUE OTORGUE EL CRÉDITO, DANDO SU APROBACIÓN INDEPENDIENTEMENTE QUE ÉSTE SEA POR UNA CUANTÍA MENOR O MAYOR AL IMPORTE SOLICITADO.</li>
                    </ul>
                </li>
                <li><strong>PRODUCTO OFERTADO.</strong> LOS TERMINOS Y CONDICIONES DEL PRODUCTO FINANCIERO OBTENIDO Y OFERTADO A "EL CLIENTE " SERÁN DETERMINADOS POR EL RESULTADO QUE ARROJE LA GESTIÓN REALIZADA POR "EL PRESTADOR DE SERVICIOS" .</li>
                <li><strong>VIGENCIA.</strong> LA VIGENCIA DEL CONTRATO SERÁ DE 45 DÍAS HÁBILES, CONTADOS A PARTIR DE LA DE LA FIRMA DEL MISMO. AGOTADO EL PLAZO YA MENCIONADO , LA PRORROGA SERÁ VOLUNTARIA PARA CUALQUIERA DE LAS PARTES, A FIN DE DAR CONTINUDAD A LA GESTIÓN CREDITICIA.</li>
                <li><strong>CANCELACIÓN Y TERMINACIÓN ANTICIPADA.</strong> SI EL CLIENTE MANIFIESTA SU DESEO DE DAR POR TERMINADA LA RELACIÓN CONTRACTUAL, ÉSTE DEBERÁ SOLICITAR POR ESCRITO A "EL PRESTADOR DE SERVICIOS" LA BAJA DE GESTIÓN, Y SI ASÍ LO AMERITARÁ EL CASO, INICIAR EL PROCEDIMIENTO DE DEVOLUCIÓN DEL PAGO REALIZADO POR "EL CLIENTE".</li>
                <li><strong>PENA CONVENCIONAL POR CANCELACIÓN ANTICIPADA.</strong> SI "EL CLIENTE" EXPRESARÁ SU DESEO DE CANCELAR ANTICIPADAMENTE LA GESTIÓN CONTRACTUAL, SERÁ APLICABLE UNA PENA DEL 6% SOBRE EL MONTO SOLICITADO, MAS EL I.V.A. VIGENTE AL MOMENTO DE LA FIRMA DEL PRESENTE.</li>
                <li><strong>DEVOLUCIONES Y PAGO COMPLEMENTARIO DE HONORARIOS.</strong> NO HABRÁ DEVOLUCIÓN DE HONORARIOS BAJO NINGUNA CIRCUNSTANCIA. SI LA LÍNEA DE CRÉDITO OBTENIDA FUERÁ MENOR A LA SOLICITADA, NO RECIBIRÁ REEMBOLSO ALGUNO DEL PAGO EROGADO. SI EL CRÉDITO OBTENIDO FUERA MAYOR AL SOLICITADO "EL CLIENTE" SE OBLIGA A PAGAR LA DIFERENCIA DE HONORARIOS QUE SE SOLICITASE.</li>
                <li><strong>MODIFICACIONES.</strong> CUALQUIER MODIFICACIÓN O ALTERACIÓN REALIZADA AL PRESENTE CONTRATO, SE DARÁ POR NULA. SI NO RATIFICARE POR ESCRITO Y FIRMADA POR AMBAS PARTES. POR LO QUE CUALQUIER CONVENIO VERBAL REALIZADO CON CUALQUIER ASESOR Y/O PERSONAL DE LA EMPRESA, QUEDARÁ SIN EFECTOS JURÍDICOS.</li>
                <li><strong>VICIOS DEL CONSENTIMIENTO.</strong> AMBAS PARTES ACUERDAN QUE ES SU LIBRE VOLUNTAD LLEVAR A CABO LA CELEBRACIÓN DEL PRESENTE CONTRATO, Y SE MANIFIESTA QUE A LA FIRMA DEL MISMO, NO EXISTE ERROR, DOLO, VIOLENCIA, MALA FE O CUALQUIER VICIO DEL CONSENTIMIENTO, POR LO QUE AMBAS PARTES RENUNCIAN A DEMANDAR SU NULIDAD POR CUALQUIER CAUSA.</li>
                <li><strong>COMPETENCIA.</strong> LA PROCURADURIA FEDERAL DEL CONSUMIDOR (PROFECO) ES COMPETENTE EN LA VÍA ADMINISTRATIVA PARA DIRIMIR CUALQUIER CONTROVERSIA QUE SE ORIGINE DE LA FIRMA DE ESTE CONTRATO.</li>
                <li></li>
            </ol>
            <p><strong>LEÍDO QUE FUÉ Y UNA VEZ HECHA LA EXPLICACIÓN DE SU CONTENIDO Y ALCANCES LEGALES, LO FIRMAN LAS PARTES</strong></p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
        </td>
    </tr>
    </tbody>
</table>
<?php include 'signature.php'; ?>